"""add size field to content

Revision ID: 597d78218984
Revises: b9543604b48d
Create Date: 2022-09-08 13:38:33.291132

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "597d78218984"
down_revision = "b9543604b48d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("original_size", sa.BigInteger(), nullable=True))
    op.add_column(
        "content", sa.Column("encrypted_size", sa.BigInteger(), nullable=True)
    )
    op.add_column("content", sa.Column("is_on_crust", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "is_on_crust")
    op.drop_column("content", "encrypted_size")
    op.drop_column("content", "original_size")
    # ### end Alembic commands ###
