"""remove content from key column

Revision ID: 5dba52bab298
Revises: 8d657e3cb650
Create Date: 2022-10-20 10:30:08.535412

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5dba52bab298"
down_revision = "8d657e3cb650"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("keys_content_id_fkey", "keys", type_="foreignkey")
    op.drop_column("keys", "content_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "keys",
        sa.Column("content_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "keys_content_id_fkey", "keys", "content", ["content_id"], ["id"]
    )
    # ### end Alembic commands ###
