"""add encryption cid field to content

Revision ID: 73d654ac193a
Revises: 8b33f1249735
Create Date: 2022-09-06 04:06:29.614786

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73d654ac193a"
down_revision = "8b33f1249735"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("encrypted_cid", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "encrypted_cid")
    # ### end Alembic commands ###
