"""add aes key field to key

Revision ID: 8b33f1249735
Revises: 4323fa6b57bb
Create Date: 2022-09-06 02:32:51.025011

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b33f1249735"
down_revision = "4323fa6b57bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("keys", sa.Column("aes_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keys", "aes_key")
    # ### end Alembic commands ###
