"""key relation in content

Revision ID: 8d657e3cb650
Revises: 597d78218984
Create Date: 2022-10-20 10:26:54.058281

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d657e3cb650"
down_revision = "597d78218984"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("key_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "content", "keys", ["key_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "content", type_="foreignkey")
    op.drop_column("content", "key_id")
    # ### end Alembic commands ###
