"""owner field for keys

Revision ID: 8f54e9339e1c
Revises: 5dba52bab298
Create Date: 2022-11-26 08:44:00.559645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f54e9339e1c"
down_revision = "5dba52bab298"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("keys", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "keys", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "keys", type_="foreignkey")
    op.drop_column("keys", "owner_id")
    # ### end Alembic commands ###
