"""add name field to content

Revision ID: b9543604b48d
Revises: 73d654ac193a
Create Date: 2022-09-06 05:02:58.627588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9543604b48d"
down_revision = "73d654ac193a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "name")
    # ### end Alembic commands ###
