from pydantic import BaseSettings, Field


class Settings(BaseSettings):
    VAULT_ADDRESS = Field(default="http://127.0.0.1:8200", env="VAULT_ADDRESS")
    VAULT_TOKEN: str

    INSTANT_STORAGE_REGION: str
    INSTANT_STORAGE_ENDPOINT: str
    INSTANT_STORAGE_ACCESS_KEY: str
    INSTANT_STORAGE_SECRET_ACCESS_KEY: str
    INSTANT_STORAGE_BUCKET_NAME: str

    PUBLIC_STORAGE_REGION: str
    PUBLIC_STORAGE_ENDPOINT: str
    PUBLIC_STORAGE_ACCESS_KEY: str
    PUBLIC_STORAGE_SECRET_ACCESS_KEY: str
    PUBLIC_STORAGE_BUCKET_NAME: str

    IPFS_HTTP_PROVIDER: str

    STORAGE_BACKEND_URL: str
    STORAGE_ADMIN_TOKEN: str

    WORKER_INSTANCE: str


settings = Settings()
