version: "3.8"

services:
  custody:
    build: .
    env_file: .env
    ports:
      - "8000:8000"

  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"
