version: "3.8"

services:
  custody:
    env_file:
      - .env.prod
    image: ghcr.io/merklebot/custody:main
    networks:
      - internal
      - bridge


networks:
  internal:
    external: true # externally created
  bridge:
    external: true
